import 'package:translator/translator.dart';

class TranslatorService {
  // GoogleTranslator to perform translations
  final GoogleTranslator _translator = GoogleTranslator();

  // This function translates the given text into the native language based on the destination inputted
  Future<String> translateText(String text, String destination) async {

    // Mapping of countries to their language codes.
    Map<String, String> countryLanguage = {
      "Afghanistan": "fa",  
      "Albania": "sq",
      "Algeria": "ar",
      "Andorra": "ca",
      "Angola": "pt",
      "Antigua and Barbuda": "en",
      "Argentina": "es",
      "Armenia": "hy",
      "Australia": "en",
      "Austria": "de",
      "Azerbaijan": "az",
      "Bahamas": "en",
      "Bahrain": "ar",
      "Bangladesh": "bn",
      "Barbados": "en",
      "Belarus": "be",  
      "Belgium": "nl", 
      "Belize": "en",
      "Benin": "fr",
      "Bhutan": "dz",
      "Bolivia": "es",
      "Bosnia and Herzegovina": "bs",  
      "Botswana": "en",
      "Brazil": "pt",
      "Brunei": "ms",
      "Bulgaria": "bg",
      "Burkina Faso": "fr",
      "Burundi": "fr",
      "Cambodia": "km",
      "Cameroon": "fr",  
      "Canada": "en",  
      "Cape Verde": "pt",
      "Central African Republic": "fr",
      "Chad": "fr",
      "Chile": "es",
      "China": "zh-cn",
      "Colombia": "es",
      "Comoros": "ar",
      "Costa Rica": "es",
      "Croatia": "hr",
      "Cuba": "es",
      "Cyprus": "el",
      "Czech Republic": "cs",
      "Denmark": "da",
      "Djibouti": "ar",
      "Dominica": "en",
      "Dominican Republic": "es",
      "Ecuador": "es",
      "Egypt": "ar",
      "El Salvador": "es",
      "Equatorial Guinea": "es",
      "Eritrea": "ti",  
      "Estonia": "et",
      "Eswatini": "en",
      "Ethiopia": "am",
      "Fiji": "en",
      "Finland": "fi",
      "France": "fr",
      "Gabon": "fr",
      "Gambia": "en",
      "Georgia": "ka",
      "Germany": "de",
      "Ghana": "en",
      "Greece": "el",
      "Grenada": "en",
      "Guatemala": "es",
      "Guinea": "fr",
      "Guinea-Bissau": "pt",
      "Guyana": "en",
      "Haiti": "fr",
      "Honduras": "es",
      "Hungary": "hu",
      "Iceland": "is",
      "India": "hi", // India has many languages; "hi" is one of the main ones
      "Indonesia": "id",
      "Iran": "fa",
      "Iraq": "ar",
      "Ireland": "en",
      "Israel": "he",
      "Italy": "it",
      "Jamaica": "en",
      "Japan": "ja",
      "Jordan": "ar",
      "Kazakhstan": "kk",
      "Kenya": "sw",
      "Kiribati": "en",
      "Kosovo": "sq",
      "Kuwait": "ar",
      "Kyrgyzstan": "ky",
      "Laos": "lo",
      "Latvia": "lv",
      "Lebanon": "ar",
      "Lesotho": "en",
      "Liberia": "en",
      "Libya": "ar",
      "Liechtenstein": "de",
      "Lithuania": "lt",
      "Luxembourg": "fr",  
      "Madagascar": "mg",
      "Malawi": "en",
      "Malaysia": "ms",
      "Maldives": "dv",
      "Mali": "fr",
      "Malta": "mt",
      "Marshall Islands": "en",
      "Mauritania": "ar",
      "Mauritius": "en",
      "Mexico": "es",
      "Micronesia": "en",
      "Moldova": "ro",
      "Monaco": "fr",
      "Mongolia": "mn",
      "Montenegro": "sr",  
      "Morocco": "ar",
      "Mozambique": "pt",
      "Myanmar": "my",
      "Namibia": "en",
      "Nauru": "en",
      "Nepal": "ne",
      "Netherlands": "nl",
      "New Zealand": "en",
      "Nicaragua": "es",
      "Niger": "fr",
      "Nigeria": "en",
      "North Korea": "ko",
      "North Macedonia": "mk",
      "Norway": "no",
      "Oman": "ar",
      "Pakistan": "ur",
      "Palau": "en",
      "Panama": "es",
      "Papua New Guinea": "en",
      "Paraguay": "es",
      "Peru": "es",
      "Philippines": "tl", 
      "Poland": "pl",
      "Portugal": "pt",
      "Qatar": "ar",
      "Romania": "ro",
      "Russia": "ru",
      "Rwanda": "rw",
      "Saint Kitts and Nevis": "en",
      "Saint Lucia": "en",
      "Saint Vincent and the Grenadines": "en",
      "Samoa": "sm", 
      "San Marino": "it",
      "Sao Tome and Principe": "pt",
      "Saudi Arabia": "ar",
      "Senegal": "fr",
      "Serbia": "sr",
      "Seychelles": "en",
      "Sierra Leone": "en",
      "Singapore": "en",
      "Slovakia": "sk",
      "Slovenia": "sl",
      "Solomon Islands": "en",
      "Somalia": "so",
      "South Africa": "af", 
      "South Korea": "ko",
      "South Sudan": "en",
      "Spain": "es",
      "Sri Lanka": "si",
      "Sudan": "ar",
      "Suriname": "nl",
      "Sweden": "sv",
      "Switzerland": "de",  
      "Syria": "ar",
      "Taiwan": "zh-tw",
      "Tajikistan": "tg",
      "Tanzania": "sw",
      "Thailand": "th",
      "Timor-Leste": "pt",
      "Togo": "fr",
      "Tonga": "en",
      "Trinidad and Tobago": "en",
      "Tunisia": "ar",
      "Turkey": "tr",
      "Turkmenistan": "tk",
      "Tuvalu": "en",
      "Uganda": "en",
      "Ukraine": "uk",
      "United Arab Emirates": "ar",
      "United Kingdom": "en",
      "United States": "en",
      "Uruguay": "es",
      "Uzbekistan": "uz",
      "Vanuatu": "en",
      "Vatican City": "it",
      "Venezuela": "es",
      "Vietnam": "vi",
      "Yemen": "ar",
      "Zambia": "en",
      "Zimbabwe": "en",
    };

    // Get the language code for the destination country,
    // default to English if the country isn't in the map.
    String languageCode = countryLanguage[destination] ?? 'en';

    // Use the translator to translate the text into the determined language.
    var translation = await _translator.translate(text, to: languageCode);
    return translation.text;
  }
}
